### ISSUE TITLE
[Suggestion] Please upload the new icon as avatar picture for `sailfishos-chum`

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/main#106]
@rinigus, please upload [the 792x792 PNG version of the new logo](https://github.com/sailfishos-chum/main/blob/main/.icons/pngs/social-media/sailfishos-chum_792x792.png) as avatar picture of [the organisation `sailfishos-chum`](https://github.com/sailfishos-chum).  If you wonder about the space around it: This is done on purpose, because at some places GitHub displays a circular clipping of avatar pictures (both, of individuals and organisations), hence this is a 560×560&nbsp;Px² icon on a 792×792&nbsp;Px² canvas, because `560 × √2 = 791,959594929`, so the logo is still fully visible when clipped circularly.  If you strongly prefer the logo to use the full space [where it is primarily displayed](https://github.com/sailfishos-chum), then upload [its 560x560 PNG version](https://github.com/sailfishos-chum/main/blob/main/.icons/pngs/sailfishos-chum_560.png).

This supersedes my former contribution and request #54, which you [kindly fulfilled in January 2022](https://github.com/sailfishos-chum/main/issues/54#issuecomment-1016769542).

### Background
I am finishing off the ["new icon" story](https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/132) (in order for it not becoming a never-ending one), after discussion and feedback was very little (most comments threw in new designs) and my tries to guide the process constructively failed.  My original intention was *not* to push my own design (I do not think it is more than mediocre, originally it was intended as an example how a simple, easy to interpret icon might look like), but all other designs do not fulfil either basic technical (an SVG, which fully adheres to [Jolla's guidelines](https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/132#issuecomment-1406135716)) and / or visual (high contrast, with a few, simple and easy to interpret graphical elements) requirements.

Actually the "finishing off" part made me [re-create my former icon drafts from the scratch](https://github.com/sailfishos-chum/sailfishos-chum-gui-installer/pull/19/files), to fully comply with Jolla's reasonable guidelines, which needed a few days of tedious work (now I do know Inkscape and basic vector graphic design workflows well).

I hope you also perceive this new icon as an improvement, I have no issue for it to become superseded by something better.  Still I will likely apply my gained knowledge for proper quality assurance: technically (properly constructed SVG), visually (contrast, simplicity, conforming to Jolla's guidelines) and WRT interpretability (easy to comprehend for all on first sight).

**Comment by rinigus** [comment]
Updated. No idea why, but it still shows old one for me on some pages. If in private mode, new logo appears. Must be some cache issue

**Comment by rinigus** [comment]
PS: now new logo is visible. Closing
