### ISSUE TITLE
[Bug] `4.5.0.25` is missing at the SailfishOS:Chum and SailfishOS:Chum-Testing repositories

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/main#115]
`4.5.0.24_{aarch64|armv7hl|i486}` is currently the most recent, supported SailfishOS release.  Hence @rinigus / @piggz please …
- Add the three targets `4.5.0.25_{aarch64|armv7hl|i486}` to [the SailfishOS:Chum repository](https://build.sailfishos.org/project/show/sailfishos:chum)
- Replace the three targets `4.5.0.24_{aarch64|armv7hl|i486}` by `4.5.0.25_{aarch64|armv7hl|i486}` at [the SailfishOS:Chum-Testing repository](https://build.sailfishos.org/project/show/sailfishos:chum:testing)

Alternatively you might grant me the right to perform these regularly required actions (i.e. each time a new version of SailfishOS is released).

**Comment by rinigus** [comment]
As far as I understood, 4.5.0.25 is made via HTTP alias to 4.5.0.24. So, while OBS target is missing, repo should be there already. See https://repo.sailfishos.org/obs/sailfishos:/chum/4.5.0.25_armv7hl/

**Comment by Olf0** [comment]
Thanks, yes, that seems to be the case.  Hence closing.

P.S.: I wonder why @lbt does not also link / redirect other point release repos to their final point release; at least for SailfishOS:Chum and SailfishOS:Chum:Testing, but possibly also for the DoD OBS-repos.  This would save quite some storage and reduce the build targets for SailfishOS:Chum(:Testing) by eliminating eight target releases with each three architectures, i.e. 24 (!) build targets:
- `4.3.0.12_*` → `4.3.0.15_*`
- `4.4.0.58_*`, `4.4.0.64_*`, `4.4.0.68_*` → `4.3.0.72_*`
- `4.5.0.16_*`, `4.5.0.18_*`, `4.5.0.19_*`, `4.5.0.21_*` → `4.3.0.24_*`

While I am a strong proponent of letting the users decide when and if (at all) they update their SailfishOS installations (due to the lack of backward compatibility for much software outside of Jolla's RPM repositories), I see no point in staying on a older point release.
