### ISSUE TITLE
ownKeepass

### ISSUE THREAD

**Issue by rinigus** [sailfishos-chum/main#12]
ownKeepass got archived at https://github.com/jobe-m/ownkeepass. Let's fork it and make it compile at OBS

**Comment by rinigus** [comment]
Would have to check which fork is the most recent and use that

**Comment by piggz** [comment]
Looking at the build instructions, probably wise to add the other required packages to chum first?

**Comment by rinigus** [comment]
I haven't looked into it yet, just wanted to write it down. probably should all dependencies properly, indeed

**Comment by rinigus** [comment]
I will look into this

**Comment by rinigus** [comment]
Took longer than expected, but it should be there in a moment - compiling in :chum after :testing was fine. Turned out, ownKeepass had few binary libraries in its source tree to satisfy its dependencies. That's removed now and greatly thanks to aerique's work was not too difficult to update packaging scripts for OBS. Will close as soon as builds in the main repository will be checked on device as well.
