### ISSUE TITLE
obs reports unable to walk on path 'sailfishos:4.1.0.24/latest_i408' 

### ISSUE THREAD

**Issue by poetaster** [sailfishos-chum/main#20]
<repository name="sailfish_latest_i486">
    <path project="sailfishos:latest" repository="latest_i486"/>
    <arch>i586</arch>
</repository>
<repository name="sailfish_latest_armv7hl">
    <path project="sailfishos:latest" repository="latest_armv7hl"/>
    <arch>armv8el</arch>
</repository>
<repository name="sailfish_latest_aarch64">
    <path project="sailfishos:latest" repository="latest_aarch64"/>
    <arch>aarch64</arch>
</repository>
<repository name="sailfish_4.1.0.24_armv7hl">
    <path project="sailfishos:4.1.0.24" repository="latest_armv7hl"/>
    <arch>armv8el</arch>
</repository>
<repository name="sailfish_4.1.0.24_aarch64">
    <path project="sailfishos:4.1.0.24" repository="latest_aarch64"/>
    <arch>aarch64</arch>
</repository>
<repository name="sailfish_4.1.0.24_i486">
    <path project="sailfishos:4.1.0.24" repository="latest_i408"/>
    <arch>i586</arch>
</repository>

**Comment by piggz** [comment]
Can you elaborate? Links to package?  Is that a typo in the title?

**Comment by poetaster** [comment]
This, in the project meta:

```
  <repository name="sailfish_4.1.0.24_i486">
    <arch>i586</arch>
  </repository>
```

**Comment by poetaster** [comment]
https://build.sailfishos.org/project/show/home:poetaster:audioworks shows a setup error. I copied the blocks from 'getingstarted'.

**Comment by piggz** [comment]
Fixed, thanks
