### ISSUE TITLE
add patchmanager to chum

### ISSUE THREAD

**Issue by Andrwe** [sailfishos-chum/main#22]
Hi,

it would be nice if you could add https://github.com/sailfishos-patches/patchmanager to chum.
The build process might be a bit more complex than default packages as different branches must be used for different OS version:
* SFOS < 4 => branch patchmanager3
* SFOS >= 4 => branch sfos4-fix

The packages already exist on openrepos (https://openrepos.net/content/coderus/patchmanager-30) for all architectures except for aarch64.
The version 3.0.65 was already running fine on Xperia X with 4.1.0.24 (armv7hl).

I hope you can add this unfortunately currently unmaintained but very good project to chum.

Regards,
Andrwe

**Comment by rinigus** [comment]
We have something in testing - https://build.merproject.org/package/show/sailfishos:chum:testing/patchmanager . I have no idea on what is its status and whether it works. Looking into _service, it is from https://github.com/b100dian/patchmanager.

/cc @b100dian - any comments regarding the status? Can patchmanager be bumped to :chum?

**Comment by b100dian** [comment]
Hi, the package is the one advertised here https://forum.sailfishos.org/t/patchmanager-patches-in-koli-4-0-1/4925/109
Basically is sfos4-fix + ash support + aarch64 support

The build for versions lower than 3.4 is disabled.
I have tested it on 4.0 and 4.1 but am on the fence (as @Andrwe says) about the 3.4 version - maybe it should be disabled too as there is a working openrepos version.

So from my point of view it can be bumped - as it has been tested by a couple of forum users

**Comment by rinigus** [comment]
OK, let's disable it then for 3.4 and bump to :chum.

**Comment by rinigus** [comment]
Done, should be compiled in few minutes. Question is now in upstreaming and eventually using https://github.com/sailfishos-patches/patchmanager in `_service`. As it is organization, I presume active patchmanager devs will get keys for that as well.

**Comment by rinigus** [comment]
Closing, as patchmanager was added by @b100dian to :chum. Feel free to discuss further in the closed issue as well.

**Comment by b100dian** [comment]
Update: for some time now patchmanager is upstreamed and the sources are from sailfishos-patches organisation.

Since then I've learned that sfos 3.4 also has /usr/lib/systemd support so if you can help enable back just the 3.4 build @rinigus that would be great. Thanks!

**Comment by rinigus** [comment]
Build was enabled - forgot to reply here.
