### ISSUE TITLE
zsh

### ISSUE THREAD

**Issue by takimata** [sailfishos-chum/main#24]
I have packaged zsh (https://github.com/takimata/zsh-packaging) and would like to transfer my repo into sailfishos-chum.
Could you give me access for this?

It already builds at OBS: https://build.merproject.org/package/show/home:takimata/zsh

**Comment by rinigus** [comment]
I think it is an excellent idea. Depending on your preference, you could either 
- transfer repo to chum. Then we will make you maintainer of that repository over here
- we can fork your repo and make you maintainer over here as well

**Comment by takimata** [comment]
Transferring is easier, I think.

**Comment by rinigus** [comment]
OK, let's do the transfer. Will wait for it ...

**Comment by takimata** [comment]
For the transfer you have to give me the permission to create public repositories on sailfishos-chum :-)

**Comment by rinigus** [comment]
To keep it simpler (so we don't have to wait for @piggz to approve it), I will just import it into chum. Just a sec

**Comment by rinigus** [comment]
Imported and invite for maintaining sent. If you think you will need to admin it (ability to delete repo), let me know - we can set that as well.

Closing issue as resolved regarding Github project - feel free to reopen if needed.

Looking forward to submission at OBS as well :)

**Comment by rinigus** [comment]
I promoted zsh to sailfishos:chum as well while disabling builds for older versions, as you did in testing. Should be compiled soon

**Comment by takimata** [comment]
Thanks! The issue can be fixed probably, but I don't care about these older releases.

**Comment by rinigus** [comment]
No problem. If someone cares they could fix it as well.
