### ISSUE TITLE
ledger repository

### ISSUE THREAD

**Issue by razcampagne** [sailfishos-chum/main#28]
Hi,

I would like to submit one more package to chum: ledger.
You can find a working setup here: https://redmine.casenave.fr/projects/ledger-spec/repository

Python bindings are disabled because it requires libboost-python3 which is not available on sfos.

Thanks!

**Comment by piggz** [comment]
Ive imported https://github.com/sailfishos-chum/ledger-spec ... i presume thats what was wanted! Do you also need us to create the OBS service files, or will you do that?
