### ISSUE TITLE
Package: python3-cairosvg

### ISSUE THREAD

**Issue by Thaodan** [sailfishos-chum/main#31]
Hey,

I want to package pyhon-cairosvg and it's dependencies for that I need the following repositories:
+ [x] python3-cairosvg  
+ [x] python3-cairocffi  
+ [x] python3-cssselect2
+ [x] python3-defusedxml
+ [x] python3-pillow
+ [x] python3-tinycss2
+ [x] python3-webencodings

**Comment by rinigus** [comment]
All repos done, please accept maintainer role in all of them. Good luck!

**Comment by Thaodan** [comment]
I need 3  more:
 + pyproject-rpm-macros
 + python3-tomli
 + python3-flit

**Comment by Thaodan** [comment]
@rinigus: Can you add python3-tomli-w?

**Comment by Thaodan** [comment]
Please remove https://github.com/sailfishos-chum/python3-pillow its unused.
