### ISSUE TITLE
Adding tools repository to chum

### ISSUE THREAD

**Issue by Thaodan** [sailfishos-chum/main#33]
For packaging newer python packages pip is required which is in tools.
Can you add the tools repository path into of chum?

**Comment by rinigus** [comment]
@Thaodan, you mean under https://build.sailfishos.org/project/meta/sailfishos:chum ? Which repo it is exactly?

**Comment by Thaodan** [comment]
> @Thaodan, you mean under
> https://build.sailfishos.org/project/meta/sailfishos:chum ? Which repo it
> is exactly?
> 
Yes however it seems that tools repo isn't needed on obs the package builds 
fine.
