### ISSUE TITLE
sailfishos-chum repository in the global section 

### ISSUE THREAD

**Issue by vigejolla** [sailfishos-chum/main#35]
Executing `ssu lr`you can see that the sailfishos-chum repository is listed in "Enabled repositories (global)". This causes potential issues during OS updates.

A safer choice would be adding the repository to user section, as those repositores are disabled during OS updates.

**Comment by piggz** [comment]
Thanks ... do you know what needs changed in the .ini file to list it in the user section?

**Comment by vigejolla** [comment]
Sorry, no idea

**Comment by piggz** [comment]
Hmm.... i _think_ user defined repos are added to /etc/ssu.ini according to the source I read.  Maybe we will have to add the repo using ssu commands during package installation, instead of adding an ini file.

**Comment by rinigus** [comment]
Looks like running, as defaultuser

```
ssu ar sfos-chum-testing 'https://repo.sailfishos.org/obs/sailfishos:/chum:/testing/%(release)_%(arch)/'
```

Actually adds repo correctly to /etc/ssu/ssu.ini . Let's see if we can also add some INI file there directly as I am not sure how we can run these days "as a user" while installing RPM.

**Comment by rinigus** [comment]
We can run that `ssu` command also from RPM SPEC as root - result is the same, it is added to users section.

**Comment by rinigus** [comment]
Fixed by @piggz
