### ISSUE TITLE
Enabling testing repositories in settings breaks chum gui

### ISSUE THREAD

**Issue by PawelSpoon** [sailfishos-chum/main#40]
i had a working installation
i have enabled testing repos checkbox
immediately after, chum gui told me that it cannot manage repos, maybe cause i have multiple ones defined

uninstal did not solve it
installing rpm package would succeed but icon would not show in launcher
now checking ssu commands to solve the problem:

my solution: 
install chumgui via zypper as per piggz blog
ssu rr sailfishos-chum
start chumgui did re-initialize ...

oh right:.
i am using gs290 / yggdrasil with sfos 4.3.0.12

**Comment by PawelSpoon** [comment]
ssu lr returns:
[root@VollaPhone features.d]# ssu lr
Enabled repositories (global): 
 - adaptation-common           ... https://releases.jolla.com/releases/4.3.0.12/jolla-hw/adaptation-common/aarch64/
[W] unknown:0 - QConnmanTechnologyInterface::scanReply() "No carrier"
 - adaptation-community        ... https://repo.sailfishos.org/obs/nemo:/testing:/hw:/volla:/yggdrasil:/4.3.0.12/sailfish_4.3.0.12_aarch64
 - adaptation-community-common ... https://repo.sailfishos.org/obs/nemo:/testing:/hw:/common/sailfishos_4.3.0.12_aarch64/
 - apps                        ... https://releases.jolla.com/jolla-apps/4.3.0.12/aarch64/
 - hotfixes                    ... https://releases.jolla.com/releases/4.3.0.12/hotfixes/aarch64/
 - jolla                       ... https://releases.jolla.com/releases/4.3.0.12/jolla/aarch64/
 - mentaljam-obs               ... http://repo.merproject.org/obs/home:/mentaljam/4.3.0.12_aarch64/
 - sailfishos-chum-yggdrasil   ... https://repo.sailfishos.org/obs/sailfishos:/chum/4.3.0.12_aarch64/

Enabled repositories (user): 
 - openrepos-Acce            ... https://sailfish.openrepos.net/Acce/personal/main
 - openrepos-Karry           ... https://sailfish.openrepos.net/Karry/personal/main
 - openrepos-Mister_Magister ... https://sailfish.openrepos.net/Mister_Magister/personal/main
 - openrepos-PawelSpoon      ... https://sailfish.openrepos.net/PawelSpoon/personal/main
 - openrepos-WerkWolf        ... https://sailfish.openrepos.net/WerkWolf/personal/main
 - openrepos-ade             ... https://sailfish.openrepos.net/ade/personal/main
 - openrepos-attah           ... https://sailfish.openrepos.net/attah/personal/main
 - openrepos-black_sheep_dev ... https://sailfish.openrepos.net/black_sheep_dev/personal/main
 - openrepos-coderus         ... https://sailfish.openrepos.net/coderus/personal/main
 - openrepos-eber42          ... https://sailfish.openrepos.net/eber42/personal/main
 - openrepos-ichthyosaurus   ... https://sailfish.openrepos.net/ichthyosaurus/personal/main
 - openrepos-llelectronics   ... https://sailfish.openrepos.net/llelectronics/personal/main
 - openrepos-martonmiklos    ... https://sailfish.openrepos.net/martonmiklos/personal/main
 - openrepos-osetr           ... https://sailfish.openrepos.net/osetr/personal/main
 - openrepos-p2501           ... https://sailfish.openrepos.net/p2501/personal/main
 - openrepos-poetaster       ... https://sailfish.openrepos.net/poetaster/personal/main
 - openrepos-rinigus         ... https://sailfish.openrepos.net/rinigus/personal/main
 - openrepos-rubdos          ... https://sailfish.openrepos.net/rubdos/personal/main
 - openrepos-slava           ... https://sailfish.openrepos.net/slava/personal/main
 - sailfishos-chum           ... https://repo.sailfishos.org/obs/sailfishos:/chum/4.3.0.12_aarch64/
 - store                     ... https://store-repository.jolla.com/yggdrasil/aarch64/?version=4.3.0.12

**Comment by piggz** [comment]
Try disabling sailfishos-chum-yggdrasil

**Comment by rinigus** [comment]
I wonder if we need special HOWTO for yggdrasil users

**Comment by PawelSpoon** [comment]
is this special to yggdrasil port of valid for any community ports ?
a note somewhere, maybe even in the gui would be sufficient.
the other problem i had:
i went to settings and wanted to show all packages and clicked instead again on the testing repo and again everything broke

so my request would be that settings page is a dialog: without commit no changes, or that testing repo switch has an remorse timer.
i just hit it by chance and had immediately again the  error message

**Comment by rinigus** [comment]
Is this for the latest version of Chum GUI? We have just released 0.4.0 which should resolve issue with yggdrasil and you should be able to switch between repos using settings as intended.

**Comment by PawelSpoon** [comment]
no that did happen 2 days back. i have retried now and switch to testing did work
also switch back seems to work

**Comment by PawelSpoon** [comment]
works with latest gui version
