### ISSUE TITLE
Beautify and adapt SailfishOS:Chum OBS-repository's description

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/main#45]
At https://build.sailfishos.org/project/meta/sailfishos:chum
please change 
```
<project name="sailfishos:chum">
  <title>SailfishOS Community repos</title>
  <description>SailfishOS Community repos&#13;
&#13;
See https://github.com/sailfishos-chum/main for documentation and issues.&#13;
&#13;
Ping piggz or rinigus at #sailfishos for help</description>
```
to
```
<project name="sailfishos:chum">
  <title>SailfishOS:Chum</title>
  <description>SailfishOS:Chum community repository&#13;
&#13;
A GUI-client for SailfishOS:Chum is available for easy installation at https://chumrpm.netlify.app/ and its individual RPMs are also provided at https://build.sailfishos.org/package/show/sailfishos:chum/sailfishos-chum-gui&#13;
A helper RPM, which solely provides an appropriate local repository configuration for utilising SailfishOS:Chum with command line tools as pkcon or zypper, is available at https://build.sailfishos.org/package/show/sailfishos:chum/sailfishos-chum&#13;
&#13;
See https://github.com/sailfishos-chum/main for documentation, guidance, rules and the issue tracker.&#13;
You may also ping piggz or rinigus at the IRC channel #sailfishos for help.&#13;</description>
```
This aligns this description and its wording with PR #44 and https://github.com/sailfishos-chum/sailfishos-chum-gui/pull/85

P.S.: I hope that my guess that `#sailfishos` denotes an IRC channel (and not some Telegram group etc.) is correct.

**Comment by rinigus** [comment]
Done. Similar notation has been used for chum:testing repo as well

- https://build.sailfishos.org/project/show/sailfishos:chum
- https://build.sailfishos.org/project/show/sailfishos:chum:testing

Please check and close the issue if it is fixed

**Comment by Olf0** [comment]
Thank you, we are almost there, but not fully yet:
* You already had Copy&Paste'd my suggestion, when I did my final edit; sorry, I tend to have after-thoughts.
* You introduced an enhancement /(additional line break) and a regression (full stop after a web-link).
* The appearance differs, when rendered by the OBS web-GUI: The central text block is too long and clumsy.
* I forgot a final line break.

Hence another try, this time separately for both pages:
1. https://build.sailfishos.org/project/show/sailfishos:chum
   ```
   <project name="sailfishos:chum">
     <title>SailfishOS:Chum</title>
     <description>SailfishOS:Chum community repository&#13;
   &#13;
   &#13;
   A full-featured GUI-client and a minimalistic helper RPM (which solely provides a local repository configuration) for utilising the SailfishOS:Chum repository are available for easy installation at https://chumrpm.netlify.app/&#13;
   &#13;
   For SailfishOS:Chum's documentation, guidance, rules and issue tracker, see https://github.com/sailfishos-   chum/main&#13;
   &#13;
   You may also ping piggz or rinigus at the IRC channel #sailfishos for help.&#13;
   &#13;
   </description>
   ```
2. https://build.sailfishos.org/project/show/sailfishos:chum:testing
   ```
   <project name="sailfishos:chum:testing">
     <title>SailfishOS:Chum:Testing</title>
     <description>SailfishOS:Chum testing repository&#13;
   &#13;
   &#13;
   This repository is used for evaluating packages before they are promoted to the main repository.&#13;
   To submit a new or updated package, create it under your own account and submit it per OBS' "Submit package" action.&#13;
   &#13;
   For SailfishOS:Chum's documentation, guidance, rules and issue tracker, see https://github.com/sailfishos-chum/main&#13;
   &#13;
   You may also ping piggz or rinigus at the IRC channel #sailfishos for help.&#13;
   &#13;
   </description>
   ```
<br />

HTH & hope that looks better than v1.

**Comment by rinigus** [comment]
Updated. Had to add one more linebreak in :testing to split the paragraphs. Hopefully, its OK now :)

**Comment by Olf0** [comment]
* For the main repository:
  For some reason the double line break after the subtitle has been reduced to a single one.  But the double line break after the subtitle is looking good at the testing repository, IMO.
* For the testing repository:
  Actually my intention was to deliberately avoid inserting a paragraph split there, just a simple line break.  Before you had both sentences directly appended to each other, hence I considered a line break to increase readability, but also to be sufficient.  IMO paragraph breaks (u.e., empty lines) are only helpful, if either a line ends with a web-link to Copy&Paste or a paragraph ends.
   I also thought of inserting the preposition "staging", so this is the / my chance.

**v3**:
1. https://build.sailfishos.org/project/show/sailfishos:chum (identical to v2!)
   ```
   <project name="sailfishos:chum">
     <title>SailfishOS:Chum</title>
     <description>SailfishOS:Chum community repository&#13;
   &#13;
   &#13;
   A full-featured GUI-client and a minimalistic helper RPM (which solely provides a local repository configuration) for utilising the SailfishOS:Chum repository are available for easy installation at https://chumrpm.netlify.app/&#13;
   &#13;
   For SailfishOS:Chum's documentation, guidance, rules and issue tracker, see https://github.com/sailfishos-   chum/main&#13;
   &#13;
   You may also ping piggz or rinigus at the IRC channel #sailfishos for help.&#13;
   &#13;
   </description>
   ```
2. https://build.sailfishos.org/project/show/sailfishos:chum:testing (solely the word "staging" added)
   ```
   <project name="sailfishos:chum:testing">
     <title>SailfishOS:Chum:Testing</title>
     <description>SailfishOS:Chum testing repository&#13;
   &#13;
   &#13;
   This staging repository is used for evaluating packages before they are promoted to the main repository.&#13;
   To submit a new or updated package, create it under your own account and submit it per OBS' "Submit package" action.&#13;
   &#13;
   For SailfishOS:Chum's documentation, guidance, rules and issue tracker, see https://github.com/sailfishos-chum/main&#13;
   &#13;
   You may also ping piggz or rinigus at the IRC channel #sailfishos for help.&#13;
   &#13;
   </description>
   ```

If you are tired of these nitpicking changes, never mind.  But they make these two texts more consistent (both with two line breaks after the subtitle) and the two sentences IMO logically form a paragraph together, so they shall not be split.

**Comment by rinigus** [comment]
Taking into account that these texts are mostly for developers and not of interest for users, I suggest to stop fine tuning them. I think they are good enough and its better to focus on more important issues

**Comment by PawelSpoon** [comment]
when we talk about the readme.md i am to stupid to understand the simplified process of check-in.  and as a consequence i bother you guys on each update with submit package requests as i just found out. can you please improve that or give me a hint ?
thanks !

**Comment by rinigus** [comment]
@PawelSpoon: yes, it is manual at this stage when we accept in sailfishos:chum. But don't worry about bothering, it is a part of the design. So, you are expected to make it ready in sailfishos:chum:testing and then make submit request 

sailfishos:chum:testing -> sailfishos:chum

We try to process ASAP, but it may take few hours depending on our timezone, work engagement.

**Comment by Olf0** [comment]
@PawelSpoon, 
> ok i did accept my own request and version now ended in :testing

Do you feel that is some information missing in the README.md?
I.e., do you think that a (half-) sentence denoting this should be added to [README.md#how-to-use-the-sailfishoschum-repository-developers-guide](https://github.com/sailfishos-chum/main/blob/main/README.md#how-to-use-the-sailfishoschum-repository-developers-guide)?
If so, can you please make a suggestion in a new issue or a PR (because the last three messages already have been off-topic for this issue).

**Comment by Olf0** [comment]
@rinigus,
> Taking into account that these texts are mostly for developers and not of interest for users, …

I would like to agree, but multiple user-guides direct users to these pages, e.g. [Announcing sailfishos:chum](https://forum.sailfishos.org/t/announcing-sailfishos-chum/7381).

> I suggest to stop fine tuning them. I think they are good enough and its better to focus on more important issues

Which in this context is to enhance the alternatives to …
1. browsing RPMs there to install them at the command line.
2. download SailfishOS:Chum repo config RPM from there to perform 1.
3. download the SailfishOS:Chum GUI app RPM from there.

* Well, I tried to address point 3 per [sailfishos-chum-web PR 4](https://github.com/sailfishos-chum/sailfishos-chum-web/pull/4), but sailfishos-chum-web seems to be unmaintained currently.  Can you trigger a review and maybe a subsequent merging and publishing (or just do that)?
* But this is still an awkward workaround, and a severe obstacle to "[become the principal software distribution platform for Sailfish OS](https://github.com/sailfishos-chum/main#sailfishoschum-community-repository-documentation-and-issue-tracker)".  The real solution might be to implement [sailfishos-chum-gui issue 96](https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/96).

**Comment by rinigus** [comment]
@Olf0: I have been thinking if we could push GUI into the official store. Not sure whether communication with SSU or PackageKit is allowed there. Haven't look into it yet, unfortunately.

**Comment by Olf0** [comment]
> @Olf0: I have been thinking if we could push GUI into the official store.

That would be a really easy and nice way out, but …
> Not sure whether communication with SSU or PackageKit is allowed there.

I doubt that.
> Haven't look into it yet, unfortunately.

Me, too.

**Comment by Olf0** [comment]
… furthermore I do not remember that the Jolla Store does support deploying different RPMs depending on the installed SailfishOS release.  If so, this approach has massive drawbacks.

IMO the only viable way is a `noarch` installer RPM, this is way I pointed to [sailfishos-chum-gui issue 96](https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/96) for a potential long-term solution.

Until then, merging [sailfishos-chum-web PR 4](https://github.com/sailfishos-chum/sailfishos-chum-web/pull/4) would bring an enhancement ("quick win") for the current workaround.

**Comment by rinigus** [comment]
I am not currently aware of the code that would require different versions on the same arch for different SFOS releases. As we fixed the issues encountered by you on older SFOS, it could work via Jolla Store. Just (most probably) we will hit some policy prohibiting it

**Comment by Olf0** [comment]
> I am not currently aware of the code that would require different versions on the same arch for different SFOS releases.

So the necessity to select an SFOS release at https://chumrpm.netlify.app/ is just a superfluous complication?!?
Then this webpage and its [source repository](https://github.com/sailfishos-chum/sailfishos-chum-web) also are good for nothing, because the SailfishOS:Chum GUI app could be easily deployed via OpenRepos?

> As we fixed the issues encountered by you on older SFOS, it could work via Jolla Store.

O.K.; that would be really nice.  If only we both would not hesitate out of experience that … 

> Just (most probably) we will hit some policy prohibiting it.

**Comment by rinigus** [comment]
> So the necessity to select an SFOS release at https://chumrpm.netlify.app/ is just a superfluous complication?!?

Yes, pretty much, I believe. 

> Then this webpage and its [source repository](https://github.com/sailfishos-chum/sailfishos-chum-web) also are good for nothing, because the SailfishOS:Chum GUI app could be easily deployed via OpenRepos?

yes, in principle. Although, it is a bit bizarre when you have to hop through OpenRepos to end up in Chum. So, we better either make it possible to install via Store or have an easier online download.

**Comment by Olf0** [comment]
> > So the necessity to select an SFOS release at https://chumrpm.netlify.app/ is just a superfluous complication?!?
> 
> Yes, pretty much, I believe.

For sure, and for both RPMs.  One is also a `noarch` RPM, thus both enforced choices are completely unnecessary for it.

> > Then this webpage and its [source repository](https://github.com/sailfishos-chum/sailfishos-chum-web) also are good for nothing, because the SailfishOS:Chum GUI app could be easily deployed via OpenRepos?
> 
> yes, in principle. Although, it is a bit bizarre when you have to hop through OpenRepos to end up in Chum. 

This would be far less bizarre than either to go to [an awkwardly looking web-page at an unknown hoster](https://chumrpm.netlify.app/), to perform two manual choices there to ultimately download an RPM, which has to be manually installed or to perform the same actions fully manually [at the SailfishOS:Chum OBS](https://build.sailfishos.org/package/show/sailfishos:chum/sailfishos-chum-gui) (which you defined as "for developers").
Especially for everybody already using Storeman, but even if one manually downloads this RPM, because OpenRepos is a well known location.

> So, we better either make it possible to install via Store or have an easier online download.

Via Jolla Store or OpenRepos does not make any difference for many, likely most SailfishOS users willing to use SailfishOS:Chum.

Though I sure support to "*have an easier online download*", this is exactly why I created [sailfishos-chum-web PR 4](https://github.com/sailfishos-chum/sailfishos-chum-web/pull/4) and [contributed to bug reports](https://github.com/sailfishos-chum/sailfishos-chum-web/issues/3#issuecomment-1025243055), only to see that no one seems to care.
But it always will be an awkward workaround, much more tedious, inconvenient and questionable (in terms of trustworthyness) than using Storeman (or the Jolla Store app).

**Comment by rinigus** [comment]
Re unknown hoster: good point. Maybe we should add those RPMs into this repo releases. We could make some version that would later be just updated at OBS. That way RPMs will be coming from a repo that is associated with the project. Although, that "unknown hoster" should be actually providing links to OBS

I am not maintainer of -chum-web and I don't know how that web app gets enrolled.

As for OpenRepos, yes, maybe we should put it there as well. 

Now in terms of making it happen - I'd love to spend a bit of time on other projects. Just few days or a week :)

**Comment by Olf0** [comment]
> Although, that "unknown hoster" should be actually providing links to OBS

Well, if I ever get stuff merged there, I have https://github.com/Olf0/sailfishos-chum-web/pull/1/commits/72d82a08395bc31f9bbb361b6f18b985b735d849 in store.

> I am not maintainer of -chum-web and I don't know how that web app gets enrolled.

Right now I would be glad to see any reaction from @mentaljam.  Piling up more issues, changes, commits and PRs does not make sense without maintainer's feedback (even silently merging would do).   

> As for OpenRepos, yes, maybe we should put it there as well.

Well, I avoided to address the consistent use of "we", but here I do have to ask who "we" is?
I could, but I would be awkward to distribute somebody else's work, and I hardly can be the maintainer at OpenRepos without being involved (at least "in the loop" / notified) of maintenance work at GitHub.  You may be better suited, but ultimately @mentaljam seems to be the "natural candidate".

**Comment by rinigus** [comment]
We would be me, @piggz, @mentaljam. I wouldn't mind you to take GUI RPMs and set them up at OpenRepos. You seem to be very well in the loop already :)

**Comment by Olf0** [comment]
> I wouldn't mind you to take GUI RPMs and set them up at OpenRepos.

Done: https://openrepos.net/content/olf/sailfishoschum-gui-client-app & https://openrepos.net/content/olf/sailfishoschum-repo-config-rpm

> You seem to be very well in the loop already :)

I am merely a contributor, who tried to enhance the visual appeal and usability of the SailfishOS:Chum infrastructure (software, documentation etc.) to a point where it looses the look & feel of being "done by students in their spare time" (a phrase a colleague of mine at work coined, which fits well to many FLOSS projects, even some "big" ones); IMO this was (and still is: a couple of PRs are not merged yet) just a first step towards a more professional appearance for many infrastructure components of SailfishOS:Chum with the long-term goal in mind of *"[The ambition is to become the principal software distribution platform for Sailfish OS](https://github.com/sailfishos-chum/main#sailfishoschum-community-repository-documentation-and-issue-tracker)"*.

As mentioned before, most techies vastly underestimate the impact of appearance on non-techies: Because they have nothing else to base their judgement upon, the "look & feel" is what they evaluate, while all the things techies are proud of (quality of the source code etc.) are (rsp., "must implicitly be") meaningless to them.

As said and now also stated in the README, I did appreciate the concept of F-Droid (a repo with semi-automatic builds from contributed sources) much for long and love to see it applied to the SailfishOS ecosystem.  This is why I supported SailfishOS:Chum by roughly enhancing an aspect which did not seem to be much in your focus yet: a proper "look & feel" (appearance and usability).

**Comment by rinigus** [comment]
This is an excellent example where we can very well contribute bits to build something bigger. I am happy that you took this part of the project and work on the design and overall appearance. It will surely translate into more users and developers working via SailfishOS:Chum :)

**Comment by rinigus** [comment]
While Chum GUI got just released (minor version bump), we can keep older GUI binaries at OpenRepos as GUI gets updated by itself through Chum anyway. So, in this respect, we need to update OpenRepos release only occasionally.

**Comment by Olf0** [comment]
> While Chum GUI got just released (minor version bump), we can keep older GUI binaries at OpenRepos as GUI gets updated by itself through Chum anyway. So, in this respect, we need to update OpenRepos release only occasionally.

Well, now "we" is me. :wink:

More seriously: Yes, I already considered that, too.

But specifically for the last upload of the sailfishos-chum-gui RPM v0.4.0, I have to redo it any way, because I did not think enough before acting: I picked the variant compiled for SailfishOS 4.3.0, which failed to install later when testing on my XperiaX@SFOS3.2.1.  That "C++ ABI mismatch" error was to be expected, in hindsight. :frowning_face:
Thus I plan to upload the sailfishos-chum-gui RPM v0.4.1 compiled for SFOS 3.1.0 at OpenRepos, next.  Do you expect any issues when installing this on recent SailfishOS releases?

**Comment by rinigus** [comment]
I was mistaken - cannot use GUI for SFOS 4.0.1 (oldest version for aarch64) on 4.3. At least not as it is now. There is something preventing it from starting when using app grid. I guess related to the bug you had with the invoker :( . 

Cannot test very old SFOS releases, unfortunately.

**Comment by Olf0** [comment]
> I was mistaken - cannot use GUI for SFOS 4.0.1 (oldest version for aarch64) on 4.3. At least not as it is now. There is something preventing it from starting when using app grid. I guess related to the bug you had with the invoker :( .

:frowning:
O.K., I deleted my recent uploads of the sailfishos-chum-gui RPM v0.4.1 compiled for SFOS 3.1.0 (rsp. SFOS 4.0.1 for aarch64) at OpenRepos, and uploaded the variants compiled for SFOS 4.3.0.

So currently it makes only sense to offer the sailfishos-chm-gui variants compiled for the current SFOS release at OpenRepos, but this is probably only useful for users of exactly this SFOS release.

Maybe [Slava Monich's harbour-lib](https://github.com/monich/harbour-lib) is helpful here for implementing a proper solution.

Until then my one-man-show at [sailfishos-chum-web PR 4](https://github.com/sailfishos-chum/sailfishos-chum-web/pull/4) would still provide a quick improvement (though only visually and WRT clarity of the text), if it is ever reviewed, maybe merged and even uploaded to [chumrpm.netlify.app](https://chumrpm.netlify.app/).

> Cannot test very old SFOS releases, unfortunately.

Well, I can, did and do (at least ARMv7A@SFOS3.2.1): Variants compiled for SFOS ≥ 3.4.0 fail, [as mentioned}](https://github.com/sailfishos-chum/main/issues/45#issuecomment-1031962307).

**Comment by rinigus** [comment]
Makes sense to have latest GUI version on OpenRepos. We will have to revise options for GUI installer and then look what to do about it. I can look into it, hopefully tonight after work

**Comment by Olf0** [comment]
This deviated far enough from the original issue topic (which is basically resolved) to be closed.

The remaining issues should be discussed elsewhere, the most prominent (and last discussed here) at [SailfishOS:Chum GUI issue 96](https://github.com/sailfishos-chum/sailfishos-chum-gui/issues/96].
