### ISSUE TITLE
Proper, representative icon is missing …

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/main#54]
… for the organisation SailfishOS:Chum, see upper left corner at [github.com/sailfishos-chum](https://github.com/sailfishos-chum).

Until a proper, representative icon is created, please re-use the minimalistic, but acceptable [icon for the SailfishOS:Chum GUI-client app](https://raw.githubusercontent.com/sailfishos-chum/sailfishos-chum-gui/main/icons/sailfishos-chum-gui.svg), rsp. a PNG export of it with transparent background, a size of ≥ 512x512 Px², 1:1 aspect ratio with square pixels (i.e., simply: a spare image) and a file size under 1 MByte.
<sub>You may also take a look at this GitHub documentation (which adds nothing to aforementioned information): [docs.github.com:Creating a custom badge](https://docs.github.com/en/developers/apps/building-github-apps/creating-a-custom-badge-for-your-github-app) and [docs.github.com:Guidelines for logos](https://docs.github.com/en/developers/github-marketplace/listing-an-app-on-github-marketplace/writing-a-listing-description-for-your-app#guidelines-for-logos).</sub>

**Comment by Olf0** [comment]
Created three bitmap images:

1. sailfishos-chum_512x512.png
    ![sailfishos-chum_512x512.png](https://user-images.githubusercontent.com/16547876/150039910-c4c84b7a-350e-476d-86ed-3afc5e9eef86.png)

2. sailfishos-chum_640x640.png
    ![sailfishos-chum_640x640.png](https://user-images.githubusercontent.com/16547876/150039914-f3c34478-ab42-4801-89d4-7bc87ab23cd0.png)

3. sailfishos-chum_768x768.png
    ![sailfishos-chum_768x768.png](https://user-images.githubusercontent.com/16547876/150039916-ae5b7cd7-fb7b-46bc-b9fe-dae4a8ff6d06.png)

**Comment by Olf0** [comment]
Due to still being less than 25 kbytes in size, I suggest using the third one: [sailfishos-chum_768x768.png](https://user-images.githubusercontent.com/16547876/150039916-ae5b7cd7-fb7b-46bc-b9fe-dae4a8ff6d06.png)

**Comment by rinigus** [comment]
Icon has been added, thank you for generating it!
