### ISSUE TITLE
adding nfs-utils (and friends) to the chum repo

### ISSUE THREAD

**Issue by nephros** [sailfishos-chum/main#56]
There is packaging of nfs-utils here: 

 - https://build.sailfishos.org/package/show/sailfishos:chum:testing/nfs-utils 
 - https://build.sailfishos.org/package/show/sailfishos:chum/nfs-utils

The following dependency packages are also on chum and chum testing:

 - [libevent](https://build.sailfishos.org/package/show/sailfishos:chum:testing/libevent)
 - [keyutils](https://build.sailfishos.org/package/show/sailfishos:chum:testing/keyutils)
 - [libtirpc](https://build.sailfishos.org/package/show/sailfishos:chum:testing/libtirpc)
 - [rpcbind](https://build.sailfishos.org/package/show/sailfishos:chum:testing/rpcbind)

All these enable a SFOS device to use NFSv3 and NFSv4.x mounts (and theoretically to act as an NFS server). 

They fall into the "actively maintained elsewhere, packaged for SFOS" category, but currently mainly use a dumb "tarball+spec in OBS" build structure.

IF there is interest in having the packaging repos for these here in the chum repo, I request these repos to be created.
I shall then migrate to standard tar_git building for them where possible.

If there is no interest in having NFS infrastructure maintained here, that's absolutely fine, just say no :)

**Comment by rinigus** [comment]
I think it will make sense to add them here. Hopefully it will make it easier for you to maintain them. I'll create them and ping you in this issue as soon as ready

**Comment by rinigus** [comment]
Done! You should get invites for all of them. Good luck!

**Comment by rinigus** [comment]
Closing here
