### ISSUE TITLE
adding davfs2 to the chum repo

### ISSUE THREAD

**Issue by nephros** [sailfishos-chum/main#57]
There is packaging of davfs here: 

 - https://build.sailfishos.org/package/show/sailfishos:chum/davfs2
 - https://build.sailfishos.org/package/show/sailfishos:chum:testing/davfs2

The following dependency packages are also on chum and chum testing:

 - [libneon](https://build.sailfishos.org/package/show/sailfishos:chum:testing/neon)

These enable a SFOS device to mount DAV URLs natively (e.g. NextCloud).

They fall into the "actively maintained elsewhere, packaged for SFOS" category.

IF there is interest in having the packaging repos for these here in the chum repo, I request these repos to be created.
I shall then migrate to standard tar_git building for them where possible.

Please also advise whether any changes to the package naming (neon vs libneon vs neon-libs vs libneon-libs) would be wise to be in line with other such library packages.

**Comment by rinigus** [comment]
I think we don't have settled naming in this case. GUI will strip "lib" from the front by default, but some libs have preference for "lib" in the name and then its set for that. I don't know much about libneon. Right now, I have created repository libneon and I think you could change it (as you are admin) to your preference.

The both repos are created, I hope it will make it easier to maintain. It will surely increase the visibility and probably would help if someone else wants to contribute to those packages

**Comment by rinigus** [comment]
Closing here.
