### ISSUE TITLE
Intent to package libzmq

### ISSUE THREAD

**Issue by takimata** [sailfishos-chum/main#59]
I'd like to provide https://github.com/zeromq/libzmq and https://github.com/zeromq/pyzmq
As always, could you create the respective repos (maybe named libzmq and python-zmq)?

edit: just saw that we have some dedicated python/python3 naming scheme. I slightly prefer the simple name without 3 but would package for python3 only...

**Comment by rinigus** [comment]
Sure, I will add repos.

**Comment by rinigus** [comment]
Done! Good luck!

Closing over here

**Comment by takimata** [comment]
@rinigus please create repos for python-packaging and python-pyparsing as well

**Comment by rinigus** [comment]
Done
