### ISSUE TITLE
Half-abandoned app: FileCase by CepiPerez (Matias Perez)

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/main#66]
As described in the [README](https://github.com/sailfishos-chum/main#submitting-abandoned-applications), I am suggesting to either adopt (i.e., fork / clone) FileCase at the [SailfishOS:Chum source repository](https://github.com/orgs/sailfishos-chum/repositories) or to just compile and package it at the SailfishOS:Chum OBS.

Its [source code is at GitHub](https://github.com/CepiPerez/filecase-sailfish), unfortunately @CepiPerez did not assign a license to it (I would suggest to default to the [Mozilla Public License 2.0 (`MPL-2.0`)](https://opensource.org/licenses/MPL-2.0) for a multitude of reasons), but [made his intention clear at OpenRepos](https://openrepos.net/comment/37513#comment-37513), that all his unmaintained software shall be FLOSS (Free, Libre, Open Source Software).

The current status AFAICS:
* [Cepi has explicitly handed over the maintenance](https://openrepos.net/comment/37732#comment-37732) to @llewelld (flypig / David  Llewellyn-Jones, a sailor).
* David did quite some maintenance by himself in Q2-2021 and some additional contributions (AFAICS primarily fixes) from @ruditimmer (Rudi Timmermans) were merged in Q3-2021.
* But no new releases were being made available at the usual locations, not in [the old repository](https://openrepos.net/content/cepiperez/filecase-0) or [a new one](https://openrepos.net/search/node/filecase) at OpenRepos, or in the Jolla Store.
* Only today I found two [releases from last year at GitHub](https://github.com/CepiPerez/filecase-sailfish/releases), a place at which regular SailfishOS users will not discover software, and from which RPMs have to be manually downloaded and installed.
* [Looking at the commit history](https://github.com/CepiPerez/filecase-sailfish/commits/master) of FileCase, it seems to be in "minimal maintenance mode" and AFAIR @CepiPerez has stated that he does not own a SailfishOS device since long.

Thus I am suggesting to make FileCase available for a broader audience, again: By offering it via the SailfishOS:Chum repository.

Side note: One topic, which is unclear to me is, if @CepiPerez wishes that [his repository](https://github.com/CepiPerez/filecase-sailfish) stays the "tip / upstream" source code repository (despite having no SFOS device AFAIR).

Opinions, suggestions how to proceed: @CepiPerez, @llewelld, @rinigus, @ruditimmer?

**Comment by CepiPerez** [comment]
Hello. It's nice to see people still using my apps. Source code is free so you can do whatever you want, same goes for FlowPlayer

**Comment by Olf0** [comment]
> … Source code is free so you can do whatever you want, same goes for FlowPlayer

Do you have a preference for a specific Free Software / Open Source Software license, for example the [Mozilla Public License 2.0 (`MPL-2.0`)](https://opensource.org/licenses/MPL-2.0) as a modern (including a patent grant), broadly compatible (to GPL, LGPL and AGPL), reciprocal license.

Or do you want to allow for your code also being used and potentially sold as proprietary software (i.e., "closed source software" / non-free software), then I suggest the [Apache License, Version 2.0 `Apache-2.0`](https://opensource.org/licenses/Apache-2.0).

Saying, "do whatever you want with the source coded" would be interpreted by most layers as putting it into the public domain, which is a really bad choice for a multitude of reasons.

Thus @CepiPerez , **please* choose a license!
If you do not know and do not care what all this is about, then please trust me and simply pick the MPL-2.0.  It is the best choice for your code to live on as Free Software and being broadly used, except for in closed-source software.

**Comment by CepiPerez** [comment]
Just merged you request. As I said, I'm happy to see my work stills usable (even when it has a lot of crap code, and I'm sorry for this). If anyone wants maintainer rights in GitHub just let me know. Regards

**Comment by Olf0** [comment]
@CepiPerez, this is currently not working well from my perspective: Merging PRs without a thorough review and some testing created more issues than it solved in the last 6 months, see issue https://github.com/CepiPerez/filecase-sailfish/issues/16#issuecomment-1060323705

So I cleaned this up (by PR https://github.com/CepiPerez/filecase-sailfish/pull/25) and created a new release (by PR https://github.com/CepiPerez/filecase-sailfish/pull/26), but these are maintainer's tasks and hence beyond a primarily organising role I was willing to take.

To resolve this, I created the [GitHub-"organisation" `cepis-sailfishos-apps`](https://github.com/cepis-sailfishos-apps) and invited you to it.  Please accept this invitation and transfer the ownership of the [FileCase repository](https://github.com/CepiPerez/filecase-sailfish/), the [FlowPlayer repository](https://github.com/CepiPerez/flowplayer-sailfish/) and possibly also the [MyAnimeList repository](https://github.com/CepiPerez/myanimelist-sailfish) to the organisation `cepis-sailfishos-apps`.  This way you can be still in control (as you apparently do not want to "archive" these repos), but I can also re-organise these repos with branch protection rules etc., plus this allows to share the reviewing tasks.
Thanks!

**Comment by Olf0** [comment]
All done, went nicely.
