### ISSUE TITLE
Which "Jolla's repos" does line 105 of the README.md address?

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/main#69]
Does [line 105 of the README.md](https://github.com/sailfishos-chum/main/blob/main/README.md?plain=1#L105) address Jolla's repositories at the SailfishOS OBS or Jolla's RPM repositories (i.e., the binary repositories)?

I assume the latter and would insert `RPM` between `Jolla's` and `repositories` to resolve this ambiguity, if that is the correct solution.

Its current source is:
`If an application is already compiled at the Sailfish&nbsp;OS OBS, simply use the "Submit package" action for the application and all its dependencies, which are not yet available as part of the SailfishOS:Chum repository or Jolla's repositories.`

**Comment by piggz** [comment]
I think it refers to both, as theyre effectively the same.  The application can be submitted, including any dependencies which are not available in the OBS/Device repositories... which contain the same binaries

**Comment by rinigus** [comment]
So, you can have an app that depends on packages from Jolla official repos - that can be submitted as it is. Some apps depend on other libs which are not available in the official repos. In this case, you would have to submit those libs to Chum repos - assuming that the libs are missing in Chum as well.

**Comment by Olf0** [comment]
@piggz, 
> I think it refers to both, as theyre effectively the same.

Not at all, IMO: This exactly the reason why I am asking.

I see three categories, for which this is not the case:
1. Proprietary packages which are part of the core SailfishOS: Lipstick (IIRC, two packages), all Silica components (many packages) and many other packages.  [This page at the Mer-Wiki provides a nice overview](https://wiki.merproject.org/wiki/SailfishOSS#Non_OSS_packages), which mostly is still correct.
2. Proprietary packages from Jolla which are not part of the core SailfishOS, but also are not applications: AlienDalvik, XT9, EAS.
3. FLOSS packages, which are not part of the core SailfishOS: In my two year long quest to find the recent sources of these additional packages, which were formerly offered in Jolla'a `mer-tools` RPM repository, I gained the impression that they are not built at the Mer- / SailfishOS-OBS.  [See here, specifically point 2](https://together.jolla.com/question/176549/state-maintenance-and-relationship-of-mer-tools-repositories/).

I even do not believe that this is the case for the *fourth category*: FLOSS packages, which are part of the core SailfishOS, i.e., [these, minus category 3 (ex-`mer-tools`)](https://wiki.merproject.org/wiki/SailfishOSS#OSS_packages).  Why else would [Jolla have been so keen on closing the Mer- / SailfishOS-OBS](https://forum.sailfishos.org/t/changes-needed-to-merge-the-project-names-to-sailfish-os/1672), if they technically depend on this infrastructure?  Thus I believe Jolla builds their packages elsewhere for long, and what exists at the Mer- / SailfishOS-OBS is not what is deployed via Jolla's RPM repositories; that may (or may not) correspond loosely, but is not suitable as a (reliable) reference. 

Off-topic question: Does any of you have a proper indication that Jolla really uses the Mer- / SailfishOS-OBS for building the packages they deploy via their RPM repos?

> The application can be submitted, including any dependencies which are not available in the OBS/Device repositories... which contain the same binaries

Sorry Adam, I completely fail to parse this statement, even after having it read at least 6 times: Grammar (e.g., the "not" seems to be accidentally inserted) and terms are unclear to me, specifically what "the OBS/Device repositories" addresses (maybe, "Jolla's OBS or RPM repositories")?  (Then "which contain the same binaries" is exactly what my OT-question questions and in this case I am really curious for the insights you might provide.)

Did you mean to state, "An application can be submitted to SailfishOS:Chum, which includes any dependencies on packages ~~not~~ available in Jolla's RPM repositories."  If so, IMO this was a quite convoluted way of answering "**Yes.**" to my original question. :wink: If not, I just completely failed to comprehend your statement.  Please either acknowledge or rectify my interpretation.

@rinigus,
> So, you can have an app that depends on packages from Jolla official repos - that can be submitted as it is.

I assume "Jolla official repos" is supposed to mean "Jolla's RPM repositories"?  I.e., a "**Yes.**" to my original question, right?

Please be aware that this includes all packages comprised of the aforementioned categories 1 to 4.
I am absolutely fine with that, because it is a clear rule, and will proceed posing a PR, which inserts "RPM" as denoted in my original question.

Additional question to both of you: Wouldn't it be better to generalise the term "application" to "package" in the paragraph we discuss here?  {Yes|No}

**Comment by piggz** [comment]
> @piggz,
> 
> > I think it refers to both, as theyre effectively the same.
> 
> Not at all, IMO: This exactly the reason why I am asking.
> 
> I see three categories, for which this is not the case:
> 
>     1. Proprietary packages which are part of the core SailfishOS: Lipstick (IIRC, two packages), all Silica components (many packages) and many other packages.  [This page at the Mer-Wiki provides a nice overview](https://wiki.merproject.org/wiki/SailfishOSS#Non_OSS_packages) (from 2016), which mostly is still correct.
> 
>     2. Proprietary packages from Jolla which are not part of the core SailfishOS, but also are not applications: AlienDalvik, XT9, EAS.
> 
>     3. FLOSS packages, which are not part of the core SailfishOS: In my two year long quest to find the recent sources of these additional packages, which were formerly offered in Jolla's `mer-tools` RPM repository, I gained the impression that they are not built at the Mer- / SailfishOS-OBS.  [See here, specifically point 2](https://together.jolla.com/question/176549/state-maintenance-and-relationship-of-mer-tools-repositories/).
> 
> 
> I even do not believe that this is the case for the _fourth category_: FLOSS packages, which are part of the core SailfishOS, i.e., [these, minus category 3 (ex-`mer-tools`)](https://wiki.merproject.org/wiki/SailfishOSS#OSS_packages). Why else would [Jolla have been so keen on closing the Mer- / SailfishOS-OBS](https://forum.sailfishos.org/t/changes-needed-to-merge-the-project-names-to-sailfish-os/1672), if they technically depend on this infrastructure? Thus I believe Jolla builds their packages elsewhere for long, and what exists at the Mer- / SailfishOS-OBS is not what is deployed via Jolla's RPM repositories; that may (or may not) correspond loosely, but is not suitable as a (reliable) reference.
> 
> Off-topic question: Does any of you have a proper indication that Jolla really uses the Mer- / SailfishOS-OBS for building the packages they deploy via their RPM repos?
> 
> > The application can be submitted, including any dependencies which are not available in the OBS/Device repositories... which contain the same binaries
> 
> Sorry Adam, I completely fail to parse this statement, even after having it read at least 6 times: Grammar (e.g., the "not" seems to be accidentally inserted) and terms are unclear to me, specifically what "the OBS/Device repositories" addresses (maybe, "Jolla's OBS or RPM repositories")? (Then "which contain the same binaries" is exactly what my OT-question questions and in this case I am really curious for the insights you might provide.)
> 
> Did you mean to state, "An application can be submitted to SailfishOS:Chum, which includes any dependencies on packages ~not~ available in Jolla's RPM repositories." If so, IMO this was a quite convoluted way of answering "**Yes.**" to my original question. wink If not, I just completely failed to comprehend your statement. Please either acknowledge or rectify my interpretation.

I mean, if applicationX depends on libraryY, and libraryY is not in the Jolla repos, then libraryY must also be submitted.

As far as categories go, to the end user, there is only the "Jolla" repository which contains all the floss/proprietary packages together (there is also store, apps, hotfixes and hw repos).  It is my understanding that Jolla _do not_ use the community OBS, they have their own private installation, and each release of sailfishos is uploaded to community OBS as a target.

But yes, if you want to insert the word RPM, feel free :)
 
> 
> @rinigus,
> 
> > So, you can have an app that depends on packages from Jolla official repos - that can be submitted as it is.
> 
> I assume "Jolla official repos" is supposed to mean "Jolla's RPM repositories"? I.e., a "**Yes.**" to my original question, right?
> 
> Please be aware that this includes all packages comprised of the aforementioned categories 1 to 4. I am absolutely fine with that, because it is a clear (and broad; i.e., not a restricting) rule, and will proceed posing a PR, which inserts "RPM" as denoted in my original question.
> 
> Additional question to both of you: Wouldn't it be better to generalise the term "application" to "package" in the paragraph we discuss here? {Yes|No}

**Comment by rinigus** [comment]
Yes, to your original question: the binary repositories of Jolla

> Off-topic question: Does any of you have a proper indication that Jolla really uses the Mer- / SailfishOS-OBS for building the packages they deploy via their RPM repos?

Jolla developers have been telling once in a while that they have their own OBS. Not the same as we use.

> Additional question to both of you: Wouldn't it be better to generalise the term "application" to "package" in the paragraph we discuss here?

Yes, that would be fine and appropriate.

**Comment by Olf0** [comment]
Many thanks to both of you for the unambiguous answers, starting with {Yes|No}.

They were crucial to phrase the result as part of PR #68 well.
