### ISSUE TITLE
emacs repository

### ISSUE THREAD

**Issue by razcampagne** [sailfishos-chum/main#7]
Hi,

I have been maintaining Emacs on OpenRepos and would like to have it on chum instead.
Main repository is here: https://git.savannah.gnu.org/git/emacs.git

Thanks!

**Comment by rinigus** [comment]
Do you have already some repository with packaging it? Or should we make a blank one and make you maintainer of it?

**Comment by razcampagne** [comment]
I have a repository for the spec file if that's what you are talking about but not on github nor on OBS: 
https://redmine.casenave.fr/projects/emacs-spec/repository

**Comment by razcampagne** [comment]
But a blank one here is fine if you prefer to have everything in one place.

**Comment by rinigus** [comment]
I imported your repository to https://github.com/sailfishos-chum/emacs and invited you as a maintainer.

To make it work at OBS, it has to be restructured a bit. See https://github.com/sailfishos-chum/mc for example. In particular:

- SPEC file should be moved to rpm subfolder
- emacs upstream should be added as submodule
- in SPEC file, you have to use something like https://github.com/sailfishos-chum/mc/blob/master/rpm/mc.spec#L50 (notice arguments to setup

If you don't have account at OBS, then I can test it there as well. When packaging, test using `mb2 ... build` - that should work as well in SDK

**Comment by rinigus** [comment]
PS: Just as a feedback - I think it makes great sense to package emacs using OBS chum. Should be way easier than fighting with all dependencies at the local build and keeping all arch variants available. Thumbs up!

**Comment by razcampagne** [comment]
Thanks!

I have been doing this without really thinking about the proper way to do it. I'll make changes according to your remarks.
I have pm'd lbt on irc to ask for an OBS account.

**Comment by razcampagne** [comment]
Package is properly building on OBS and request to chum:testing has been sent and even accepted. Thanks!
I'll close this ticket then.
