### ISSUE TITLE
Please update the "Description" field of the GitHub-"About" for sailfishos-chum/main

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/main#73]
Hurray, I am almost finished with making all the descriptions, headlines and terms concise and consistent throughout the SailfishOS:Chum "ecosystem".

One thing left to align is the "**About**" (at the upper right of [the GitHub front-page for sailfishos-chum/main](https://github.com/sailfishos-chum/main)), so it additionally mentions the repository configuration helper RPMs also hosted and maintained here (which the current text "Documentation and issues" lacks).

Thus I am kindly asking a maintainer of this repository to click on the gear icon at the upper right of [the GitHub front-page for sailfishos-chum/main](https://github.com/sailfishos-chum/main) (to the right of the text "**About**") and fill the "Description" field with:

SailfishOS:Chum Documentation, Issue tracker and repository configuration RPM

**Comment by rinigus** [comment]
Done!
