### ISSUE TITLE
[Metadata.md] `URL:` is used as `Repo:`, if not set or chum-metadata competely missing

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/main#78]
When the `Repo:` field of the SailfishOS:Chum meta-data is not set (e.g., because the SailfishOS:Chum meta-data is missing), please check if the `URL:` field in the RPM spec file header section contains either `gitlab.com` or `github.com` and use it as `Repo:` URL subsequently (i.e., also for automatically determining the SailfishOS:Chum meta-data `Url:` sub-fields).

**Comment by rinigus** [comment]
That is the way it should work already with RPM SPEC URL used as a fallback for Url/Repo. Now I can see it is not mentioned in Metadata.md

**Comment by Olf0** [comment]
> That is the way it should work already with RPM SPEC URL used as a fallback for Url/Repo. Now I can see it is not mentioned in Metadata.md

… and I should not blindly listen to people without checking everything by oneself: Sorry!

Well, at least this issue report resulted in something meaningful.

**Comment by Olf0** [comment]
Yes.
