### ISSUE TITLE
Embedded Common-Lisp and Qt5 bindings repositories

### ISSUE THREAD

**Issue by razcampagne** [sailfishos-chum/main#8]
Hi again,

I have also been maintaining ecl and eql5 packages (a framework for using Qt5 in common-lisp) on OpenRepos and I would like to have them on chum.

Repositories are here but will need some rework as per https://github.com/sailfishos-chum/main/issues/7 :
https://redmine.casenave.fr/sfos/ecl-spec.git
https://redmine.casenave.fr/sfos/eql5-spec.git

Thanks!

**Comment by rinigus** [comment]
I have added the repositories to Github and invited you as a maintainer. As the links above didn't work, couldn't import the repositories properly. But you can import it on your side by pushing to sailfishos-chum repos as into new remote, if you wish.

**Comment by razcampagne** [comment]
These packages have been imported into chum.
closing…
