### ISSUE TITLE
Package: python3-wheel

### ISSUE THREAD

**Issue by takimata** [sailfishos-chum/main#82]
I've packaged python3-wheel for Chum. Could you create a repo for it (repo name `python-wheel`)?

**Comment by rinigus** [comment]
Is repo name expacted to be python-wheel or python3-wheel?

**Comment by rinigus** [comment]
Done and you have been added as admin. Closing here

**Comment by rinigus** [comment]
https://github.com/sailfishos-chum/python-wheel

**Comment by takimata** [comment]
> you have been added as admin

Not yet :-)

**Comment by rinigus** [comment]
You have to approve the invite which should have been sent to your email

**Comment by takimata** [comment]
Ah, there it is. Thanks!
