### ISSUE TITLE
Moving my packaging repos to Chum

### ISSUE THREAD

**Issue by nephros** [sailfishos-chum/main#84]
Hello, I am  looking into moving some of the software I merely package and not maintain/write here, with the goals:

 - to ease collaborative maintainance.  
 - where chum packages are currently in tar+spec format, they will br tar_gitted 
 - (And I want to clean out my github/gitlab/openrepos collections.)

For this I ask for either of these repos be created here.  
Feel free to not do it for any of those that you think should not be here - I don't want to cause unnecessary work or clutter.

| Package | currently in chum/testing | current packaging | proposed repo name here| 
| ----------| ------------------------- | -------------------- | ------------------------|
| AtomicParsley | yes | https://gitlab.com/nephros/openrepos-atomicparsley | atomicparsley |
| ImageMagick | yes | https://gitlab.com/nephros/harbour-imagemagick | ImageMagick |
| aria2 | yes | as tarball+spec on chum | aria2 |
| detox | yes | as tarball+spec on chum | detox |
| dstat/dool | yes | https://gitlab.com/nephros/harbour-dstat  | dool |
| hardlink | yes | as tarball+spec on chum | hardlink |
| inotify-tools | yes | as tarball+spec on chum | inotify-tools |
| keychain | yes | https://gitlab.com/nephros/openrepos-keychain | keychain |
| mytraceroute | yes | https://gitlab.com/nephros/openrepos-mtr | mtr |
| ncdu  | yes | as tarball+spec on chum | ncdu  |
| nethogs | yes | https://gitlab.com/nephros/openrepos-nethogs | nethogs |
| nload | yes | https://gitlab.com/nephros/openrepos-nload | nload |
| nocache | yes | as tarball+spec on chum | nocache |
| parallel | yes | as tarball+spec on chum | parallel |
| smem | no |  http://gitlab.com/nephros/openrepos-smem | smem |
| sysstat| yes | as tarball+spec on chum  | sysstat |
| xtail | yes | as tarball+spec on chum | xtail |
| lnav | no | as tarball+spec on [my OBS](https://build.sailfishos.org/package/show/home:nephros:devel/lnav) | lnav |

Notes on relocating the packaging repo from elsewhere:

Some of my packaging repos have quite a messy git history. As it is not important for most things, I plan to not clone but start afresh here. Unless there is a clever way to clone *one branch* into a fresh git repo? My obs-specific branches tend to be clean enough.

**Comment by nephros** [comment]
> That is a decent number of repos. I don't see any reason for not adding them here. I will look into how I can create them via cmd line

I you find out let me know ;) I haven't managed to do that using the official gitlab cli tool so far.

**Comment by rinigus** [comment]
Looks like it is possible. Requested in https://github.com/cli/cli/issues/2807. Solution seems to mix in a script gh with its extension https://github.com/mislav/gh-repo-collab

Let's see if it works ...

**Comment by rinigus** [comment]
Seems to be simple enough:

```
gh repo-collab list sailfishos-chum/atomicparsley
gh repo-collab add sailfishos-chum/atomicparsley nephros --permission admin
```

Now just will make short script and make all the repos

**Comment by rinigus** [comment]
... and done! Please accept the invitations for joining as admin. Good luck with moving the projects!

**Comment by nephros** [comment]
Nice! Thanks for everything!

**Comment by nephros** [comment]
Migration status after todays session:


|M|A|T|S| Package       | legacy packaging                                      | chum repo name|
|-|-|-|-| --------------| ----------------------------------------------------- | --------------|
| | | | | AtomicParsley | https://gitlab.com/nephros/openrepos-atomicparsley    | atomicparsley |
| | | | | ImageMagick   | https://gitlab.com/nephros/harbour-imagemagick        | ImageMagick |
| | | | | keychain      | https://gitlab.com/nephros/openrepos-keychain         | keychain |
| | | | | mytraceroute  | https://gitlab.com/nephros/openrepos-mtr              | mtr |
| | | | | dstat/dool    | https://gitlab.com/nephros/harbour-dstat              | dool |
|f|f|f|s| smem          | http://gitlab.com/nephros/openrepos-smem              | smem |
| | | | | nethogs       | https://gitlab.com/nephros/openrepos-nethogs          | nethogs |
| | | | | nload         | https://gitlab.com/nephros/openrepos-nload            | nload |
|f|n| | | aria2         | as tarball+spec on chum                               | aria2 |
|f|n| | | detox         | as tarball+spec on chum                               | detox |
|f|n| | | hardlink      | as tarball+spec on chum                               | hardlink |
|f|n|f| | inotify-tools | as tarball+spec on chum                               | inotify-tools |
|f|n|f| | ncdu          | as tarball+spec on chum                               | ncdu  |
|f|n| | | nocache       | as tarball+spec on chum                               | nocache |
|f|f| | | parallel      | https://github.com/nephros/parallel                   | parallel |
|f|n| | | sysstat       | as tarball+spec on chum                               | sysstat |
|f|n| | | xtail         | as tarball+spec on chum                               | xtail |
|f|n| |!| lnav          | as tarball+spec on my OBS                             | lnav |

M: migrated from old packaging
A: archived old packaging
T: tested
S: submitted to chum (proper, not testing)

i: in progress
f: migration/build finished
n: not applicable
s: submitted
a: accepted
!: some problem (build failure, DoD problem, ...)
