### ISSUE TITLE
[abandoned app]: Stellarium on Sailfish OS

### ISSUE THREAD

**Issue by DrYak** [sailfishos-chum/main#85]
I would like to host the abandoned Stellarium app on SailfishOS:chum repo.

Stellarium is a very nice planetarium application, that has a mobile version.

Two variants exist on openrepos:
 - a much older version [Stellarium SFM](https://openrepos.net/content/matsav/stellarium-sfm) that was ported to Sailfish by matsav, and that [avairus has managed to recompile for modern Aarch64](https://openrepos.net/content/aviarus/stellarium-sfm).
 - a more recent version [Stellarrium Mobile](https://openrepos.net/content/fooxl/stellarium-mobile) ported this time by @fuchsmisch, based on the [UbuntuTouch version 0.3](https://github.com/lduboeuf/Stellarium-mobile) by @lduboeuf, it-self based on [Stellarium Android](https://github.com/chengxinlun/Stellarium-android).
 
The second version is the one I have enjoyed on my previous Xperia XA2 Ultra, but it doesn't have an Aarch64 package, and aviarus reports not managing to get that one to compile.
 
I have [managed to rebase it](https://github.com/DrYak/Stellarium-sailfishos) against upstream UbuntuTouch's Stellarium Mobile 0.4 (based on Stellarium Android 0.12.3, using the mobile stellarium core 1.29.6) and successfully compiled it inside [CODeRUS' docker](https://github.com/CODeRUS/docker-sailfishos-platform-sdk) and test on real Aarch64 hardware.

@fuchsmich has left the SailfishOS scene (the repos on github is now archived) and thus won't be maintaining the app any more, but mentionned being fine with the App moved to the abandoned Apps in SailfishOS:chum.
 
 
 So would accept moving [my fixed fork](https://github.com/DrYak/Stellarium-sailfishos) inside SailfishOS:chum? Thank you very much.

**Comment by rinigus** [comment]
Yes, sure, we can accept the fork. Let me know how to proceed. Do you want to transfer the ownership to sailfishos-chum or should we make a new fork? I will set you as maintainer for the local repo and then you can work on it directly.

**Comment by DrYak** [comment]
Thank you very much!

Transfer of ownership (but I think I need to first have some access rights to sailfishos-chum in order to initiate this. I tried send ing a request earlier, but didn't work out).

Also, my OBS account has expired after all this years (last time was 7 years ago) but I haven't managed to meet lbt on #sailfishos yet.

**Comment by DrYak** [comment]
Well, I managed to fix the PEBKAC and copy-paste the correct password (the renames got me and my pw manager confused).

[Here](https://build.sailfishos.org/package/show/home:DrYak/stellarium) are the test build package from OBS

**Comment by rinigus** [comment]
Try to transfer the ownership again. I think it used to work before ... If it still fails, I will make a fork

**Comment by DrYak** [comment]
Hi, I've tried again, but despite the _Transfer repository_ form saying:
> Transferring may be delayed until the new owner approves the transfer.
 
it still ends up with message:
> You don’t have the permission to create public repositories on sailfishos-chum

[According to GitHub documentation](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository), "_To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization._"

So the two solutions would be:
 - Either I need (temporarily) rights of repository creation on sailfishos:chum (so I can initiate the transfer, then you can remove the granted rights).
 - Or you fork -- I would recommend forking [the original fooxl's fork](https://github.com/fuchsmich/Stellarium-mobile) (for proper attributions), [branch sailfish](https://github.com/fuchsmich/Stellarium-mobile/tree/sailfish), and I'll then overwrite my changes.

**Comment by rinigus** [comment]
It is forked fully to https://github.com/sailfishos-chum/Stellarium-mobile and you are set as admin in that repo. From here, you can take over :) 

Feel free to loose the fork status, open issues in that repo as well. Otherwise all issues will be opened in the original repo.

**Comment by rinigus** [comment]
Just don't forget to accept admin status.

**Comment by DrYak** [comment]
Thank you very much.
