### ISSUE TITLE
new repo request: Bugger

### ISSUE THREAD

**Issue by nephros** [sailfishos-chum/main#86]
Request a new Repo for application "Bugger/harbour-bugger".

It's an UI for submitting bugreports to the Forum, in the Bug Coordination Team defined format.

It would be god to have Chum as platform to cooperatively develop it.

A preview version can be evaluated here: https://build.merproject.org/package/show/home:nephros:devel/bugger

**Comment by rinigus** [comment]
Repo has been added at https://github.com/sailfishos-chum/bugger and you are admin. Good luck!
