### ISSUE TITLE
chum is not working on latest vanha rauma 4.4.0.72

### ISSUE THREAD

**Issue by legacychimera247** [sailfishos-chum/main#89]
hello everybody, everytime i pen chum (the gui) it says it's refreshing its repositories but then no app is shown

yesterday was working so maybe it's something related to today's update?

**Comment by rinigus** [comment]
It happens with every SFOS update - OBS is always bit behind. You can always point towards older release in Chum GUI Settings

**Comment by legacychimera247** [comment]
oh, thank you, it works now

**Comment by Olf0** [comment]
IOW: RTFM!
