### ISSUE TITLE
new repo request: (lib)pcre2

### ISSUE THREAD

**Issue by nephros** [sailfishos-chum/main#90]
Please add a new repo for the pcre2 library.

An example build is at https://build.merproject.org/package/show/home:nephros:branches:sailfishos:chum:testing/pcre2, adapted from the OpenSUSE spec.

This seems to be a common dependency, but is not available from Jolla AFAICS.

**Comment by rinigus** [comment]
Added https://github.com/sailfishos-chum/pcre2 and you are invited as admin. Good luck!

**Comment by nephros** [comment]
Holy moly that was fast. Thanks!
