### ISSUE TITLE
[Suggestion] Switch off "Discussions"

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/main#95]
#### DESCRIPTION

I suggest to switch off GitHub's ["Discussions" for this repo](https://github.com/sailfishos-chum/main/discussions), because the Patchmanager team tried to utilise them a year ago, concluding after three months to stop this experiment, because "Discussions" are a weak spot in GitHub's web-frontend. In contrast to that GitHub's "Issues" can be easily customised to handle all kinds of requests, which I did for ["Bugs", "Help requests" and "Feature suggestions"](https://github.com/sailfishos-chum/main/issues/new/choose), each issues can carry useful attributes (assignee, extensible labels etc.), has useful state information (open, closed with \<reason\> etc.), and GitHub's "Issues" offer a well working search with filters for all this metadata.  "Discussions" lack most of these, and the little metadata is awkward to handle and search for. Furthermore the "conversion" of a "Discussion" to an "Issue" is not really useful: It just uses the title to open a new issue report with this title.

Luckily nobody has started a discussion yet, so this feature can be switched off in the repository settings (in contrast to Patchmanager).

P.S.: The same applies to all SailfishOS:Chum source code repositories here, where no "Discussion" was ever started.

**Comment by rinigus** [comment]
@Olf0, Discussions are not enabled in these repos. Its rather confusing by GitHub, they show this tab for Maintainers only. See small text under "Get Started" on Discussion page. Look at the repo in "private" mode and you see that the discussion tab would disappear. Closing

**Comment by Olf0** [comment]
> @Olf0, Discussions are not enabled in these repos.

Well, "Yes" and "No", it is a two step process: The first step in the repo settings is on by default, the second step is to "setup discussions", as GitHub calls it.

> Its rather confusing by GitHub, they show this tab for Maintainers only. 

I know and probably I should have been more concise: Please disable in the top repository setting page (Settings "tab"), in the section "Features" the checkbox "Discussions".  This disables the "Discussions tab" for all views (including maintainers) and makes it much less likely for somebody to switch it on spontaneously, because it seems to be a "good idea" (I am sometimes a good candidate for that late at night, but not any longer for GH-discussions).

**Comment by rinigus** [comment]
It is disabled already:

![image](https://user-images.githubusercontent.com/15706605/219953557-342985c0-65b6-407b-bbdf-a60daaed5d46.png)

**Comment by Olf0** [comment]
Thank you for clarifying.

So it is up to me to determine why switching this setting off for the GitHub repos [sailfishos-chum-gui](https://github.com/sailfishos-chum/sailfishos-chum-gui) and [sailfishos-chum-gui-installer](https://github.com/sailfishos-chum/sailfishos-chum-gui-installer) made a difference for me (as I had to look at them in the maintainer capacity to do that), but not here.  Or I will just leave that as one of the few GitHub-settings conundrums.

Sorry for bugging you with this!
