### ISSUE TITLE
[Suggestion] Move the Repo Config RPM(s) out of the "main" repo to a new repo "sailfishos-chum" and then rename its spec file to "sailfishos-chum.spec"

### ISSUE THREAD

**Issue by Olf0** [sailfishos-chum/main#99]
#### DESCRIPTION
https://github.com/sailfishos-chum/main/blob/main/rpm/sailfishos-chum.rpmlintrc#L37-L41
This is by the current design of this source-repository's structure.  IMO it makes sense to rename spec file to "sailfishos-chum.spec" and move the Repo Config RPM(s) out of the "main" repo to a new repo "sailfishos-chum".'

#### ADDITIONAL INFORMATION
Too tired to flesh it out now: will do sometime.

**Comment by rinigus** [comment]
Sorry, somehow this issue slipped my attention. Thank you for reminder. I agree, that would make sense. Repository added https://github.com/sailfishos-chum/sailfishos-chum and you are admin of it.

**Comment by Olf0** [comment]
Cloned and deleted original files via PR #101.
